### ISSUE TITLE
Error after entering token

### ISSUE THREAD

**Issue by ukrolelo** [escomputers/freepbx-docker#24]
root@pbx:~/pbx# docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS         PORTS                                       NAMES
3dc9590076f3   vault:custom           "docker-entrypoint.s…"   4 seconds ago   Up 3 seconds   0.0.0.0:8100->8100/tcp, :::8100->8100/tcp   vault
e4e1d4406314   vault-transit:custom   "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes   0.0.0.0:8200->8200/tcp, :::8200->8200/tcp   pbx-vault-transit-1
7e466d035fb3   mysql:5.7              "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes   3306/tcp, 33060/tcp                         pbx-db-1
root@pbx:~/pbx# docker exec -it vault sh /usr/local/bin/configure.sh
Get "http://127.0.0.1:8100/v1/sys/seal-status": dial tcp 127.0.0.1:8100: connect: connection refused
Token (will be hidden):
Error authenticating: error looking up token: Get "http://127.0.0.1:8100/v1/auth/token/lookup-self": dial tcp 127.0.0.1:8100: connect: connection refused
Error uploading policy: Put "http://127.0.0.1:8100/v1/sys/policies/acl/administrator-policy": dial tcp 127.0.0.1:8100: connect: connection refused
Error creating token: Post "http://127.0.0.1:8100/v1/auth/token/create": dial tcp 127.0.0.1:8100: connect: connection refused
Please copy the following token to keep using Vault:

Not enough arguments (expected 1 or -self, got 0)
Token (will be hidden): root@pbx:~/pbx#

**Comment by escomputers** [comment]
not enough info
