### ISSUE TITLE
Error on docker-compose up

### ISSUE THREAD

**Issue by dchrostowski1** [escomputers/freepbx-docker#25]
Error response from daemon: pull access denied for vault-transit, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by escomputers** [comment]
Just tested it out and everything is working as expected.

OS: `VERSION="24.04 LTS (Noble Numbat)"`
Docker:
```
Client: Docker Engine - Community
 Version:           27.0.2
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        912c1dd
 Built:             Wed Jun 26 18:47:25 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.2
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       e953d76
  Built:            Wed Jun 26 18:47:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
Steps done:
`printf "your-mysql-root-password" > mysql_root_password.txt`

# Create password for Freepbx user
`sed -i "s/'password'/'your-password'/g" init.sql`

# Set proper file permissions
`chmod 600 mysql_root_password.txt`

# Build images, run database + vault transit and configure RTP ports
`sudo bash build.sh`
