### ISSUE TITLE
Vault container rebooting every 5 seconds 

### ISSUE THREAD

**Issue by kaciker** [escomputers/freepbx-docker#26]
Hello,

I have installed several versions of FreePBX in Docker while trying to reduce the resource usage of a VM (under Proxmox), as my usage is minimal and only involves forwarding calls to a mobilephone from a VTO (doorbell), but never achivied to make the video/sound works.

I came across this repository and followed the instructions to install it multiple times. However, I always encounter the same error at the same point.

I have tried this in a privileged and not, LXC container on Proxmox, using fresh Ubuntu 24, Debian 10, and Debian 12 servers.

These are the steps, let me know if more info is needed

After running build.sh 
![image](https://github.com/user-attachments/assets/dbb181d7-dd30-4959-a045-a6e964618958)
![image](https://github.com/user-attachments/assets/0ae542cb-44de-4d43-99a9-f0d32c91e878)

next step with token generation
![image](https://github.com/user-attachments/assets/504017ef-d724-42db-8a92-417d2c53d198)

After run second vault 
![image](https://github.com/user-attachments/assets/ddcb24a4-7d7f-4791-87fb-0f6974994dce)

And then, I can not run docker exec -it vault sh /usr/local/bin/configure.sh because the container is allways restarting

![image](https://github.com/user-attachments/assets/a8a617d3-1c4d-4637-ae84-729bf8d3981e)

this is the log for the conteiner vault:

`root@freepbxub24:~/freepbx-docker# docker logs vault
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
2024-12-28T11:09:59.840Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
2024-12-28T11:10:10.826Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
2024-12-28T11:10:19.873Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
2024-12-28T11:10:29.909Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
2024-12-28T11:10:40.097Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
2024-12-28T11:10:50.231Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
2024-12-28T11:11:00.764Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
2024-12-28T11:11:13.180Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
2024-12-28T11:11:28.635Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
2024-12-28T11:11:50.100Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
2024-12-28T11:12:24.014Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
2024-12-28T11:13:23.826Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
2024-12-28T11:14:32.875Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""
Error parsing Seal configuration: Error making API request.

URL: PUT http://vault-transit:8200/v1/transit/encrypt/autounseal
Code: 500. Errors:

* error performing token check: failed to look up namespace from the token: no namespace
2024-12-28T11:15:42.442Z [INFO]  proxy environment: http_proxy="" https_proxy="" no_proxy=""`

This is the log for the transit container:
![image](https://github.com/user-attachments/assets/fc410363-8a12-4d64-a541-b996f29cae3b)

GPT checks :P

![image](https://github.com/user-attachments/assets/a50633d7-908d-4364-bd94-fa9c7a9b21d3)

Can you help me ? 
I can deploy any kind of SO server to do more test if needed

**Comment by escomputers** [comment]
Hi @kaciker 
I just finished running some tests on a fresh EC2 instance with Ubuntu 24.04.1 LTS (6.8.0-1018-aws x86_64) and Docker Engine 27.2.0, following exactly the steps described in the README file and I didn’t encounter the issue you mentioned. 

As you can see, the containers are up and running without any restarts.
<img width="895" alt="image" src="https://github.com/user-attachments/assets/48012e32-6927-46ba-9260-af93aa9c85a3" />


So, I suggest testing it on a machine **outside** the Proxmox environment.
